const columns = [
  { name: 'ID', uid: 'id', sortable: true },
  { name: 'TICKET ID', uid: 'ticket id' },
  { name: 'TICKET SUBJECT', uid: 'ticket subject' },
  { name: 'ASSIGNED STAFF', uid: 'assigned staff' },
  { name: 'CREATED DATE', uid: 'created date' },
  { name: 'LAST REPLY', uid: 'last reply' },
  { name: 'PRIORITY', uid: 'priority' },
  { name: 'NAME', uid: 'name', sortable: true },
  { name: 'AGE', uid: 'age', sortable: true },
  { name: 'ROLE', uid: 'role', sortable: true },
  { name: 'TEAM', uid: 'team' },
  { name: 'EMAIL', uid: 'email' },
  { name: 'STATUS', uid: 'status', sortable: true },
  { name: 'BUDGET', uid: 'budget' },
  { name: 'DUE', uid: 'due' },
  //   { name: 'ACTIONS', uid: 'actions' },
  { name: 'ACTIONS', uid: 'actions' },
]

const statusOptions = [
  { name: 'Active', uid: 'active' },
  { name: 'Paused', uid: 'paused' },
  { name: 'Vacation', uid: 'vacation' },
]

const users = [
  {
    id: 1,
    name: 'Seun Twaio',
    role: 'CEO',
    team: 'Management',
    status: 'active',
    age: '29',
    avatar:
      'https://media.istockphoto.com/id/172316242/photo/traditional-wear.jpg?s=612x612&w=0&k=20&c=yJJUq71Vrc83JZ7b4CH3DYTy3l7GuDvZ6VfTT4NCT6M=',
    email: 'tony.reichert@example.com',
    budget: '$1,200',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'internent',
    lastReply: '12/02/2014',
    priority: 'low',
  },
  {
    id: 2,
    name: 'Ola Joseph',
    role: 'Tech Lead',
    team: 'Development',
    status: 'paused',
    age: '25',
    avatar:
      'https://media.istockphoto.com/id/1162121648/photo/portrait-of-a-young-african-student.jpg?s=612x612&w=0&k=20&c=rTl-nR5EUAckz0lxabcCosCs2OWcmzQsl2oFWRxdWuA=',
    email: 'zoey.lang@example.com',
    budget: '$200',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'internent',
    lastReply: '12/02/2024',
    priority: 'high',
  },
  {
    id: 3,
    name: 'Omonigho John',
    role: 'Sr. Dev',
    team: 'Development',
    status: 'active',
    age: '22',
    avatar:
      'https://images.unsplash.com/photo-1530785602389-07594beb8b73?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bmlnZXJpYW4lMjBnaXJsfGVufDB8fDB8fHww',
    email: 'jane.fisher@example.com',
    budget: '$1,000',
    timeline: 'overdue',
    ticketID: 'tik1423',
    ticketSub: 'rent',
    lastReply: '12/02/2024',
    priority: 'low',
  },
  {
    id: 4,
    name: 'Faith Abiudun',
    role: 'C.M.',
    team: 'Marketing',
    status: 'vacation',
    age: '28',
    avatar:
      'https://images.unsplash.com/photo-1602342323893-b11f757957c9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bmlnZXJpYW4lMjBnaXJsfGVufDB8fDB8fHww',
    email: 'william.howard@example.com',
    budget: '$4,200',
    timeline: 'overdue',
    ticketID: 'tik1293',
    ticketSub: 'laptop',
    lastReply: '12/03/2024',
    priority: 'meduim',
  },
  {
    id: 5,
    name: 'Gbenga Samuel',
    role: 'S. Manager',
    team: 'Sales',
    status: 'active',
    age: '24',
    avatar:
      'https://media.istockphoto.com/id/517302398/photo/portrait-of-nigerian-man-with-beard-looking-at-camera.jpg?s=612x612&w=0&k=20&c=BC5pdsmTWzmFO3mIlA7TQAIECnJ7Kpd-daL6G4RJqT4=',
    email: 'kristen.cooper@example.com',
    budget: '$1,400',
    timeline: 'overdue',
    ticketID: 'tik1123',
    ticketSub: 'laptop',
    lastReply: '11/02/2020',
    priority: 'low',
  },
  {
    id: 6,
    name: 'Tosin Baba',
    role: 'P. Manager',
    team: 'Management',
    age: '29',
    avatar:
      'https://media.istockphoto.com/id/960218124/photo/portrait-of-a-smiling-african-man.jpg?s=612x612&w=0&k=20&c=0wMm1uul7odMqayFPJuKVCCPwY0hL4xHntfDg51qYgQ=',
    email: 'brian.kim@example.com',
    status: 'Active',
    budget: '$1,900',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'wifi',
    lastReply: '11/02/2022',
    priority: 'low',
  },
  {
    id: 7,
    name: 'Babatunde Christ',
    role: 'Designer',
    team: 'Design',
    status: 'paused',
    age: '27',
    avatar:
      'https://media.istockphoto.com/id/1729889021/photo/happy-african-american-man-looking-at-the-camera-portrait-picture.jpg?s=612x612&w=0&k=20&c=4eAAM2hxKVqCVD5mXcDo_nV_iu4zdAbJLhpLyH7D4RI=',
    email: 'michael.hunt@example.com',
    budget: '$1,800',
    timeline: 'paid',
    ticketID: 'tik2223',
    ticketSub: 'laptop',
    lastReply: '11/02/2024',
    priority: 'high',
  },
  {
    id: 8,
    name: 'Samantha Chidi',
    role: 'HR Manager',
    team: 'HR',
    status: 'active',
    age: '31',
    avatar:
      'https://images.unsplash.com/photo-1602342323893-b11f757957c9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bmlnZXJpYW4lMjBnaXJsfGVufDB8fDB8fHww',
    email: 'samantha.brooks@example.com',
    budget: '$9,200',
    ticketID: 'tik1283',
    ticketSub: 'internent',
    lastReply: '11/02/2022',
    priority: 'low',
  },
  {
    id: 9,
    name: 'Chidebere Emmanuel',
    role: 'F. Manager',
    team: 'Finance',
    status: 'vacation',
    age: '33',
    avatar:
      'https://media.istockphoto.com/id/170617173/photo/confident-african-man.jpg?s=612x612&w=0&k=20&c=z70QyyDs34qV5dyUi-aGpVrHYamd259LFU_3NQXBFFo=',
    email: 'frank.harrison@example.com',
    budget: '$1,200',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'internent',
    lastReply: '11/02/2024',
    priority: 'medium',
  },
  {
    id: 10,
    name: 'Ayomide Adams',
    role: 'Ops Manager',
    team: 'Operations',
    status: 'active',
    age: '35',
    avatar:
      'https://images.unsplash.com/photo-1586171984069-1dbce3573a10?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bmlnZXJpYW4lMjBnaXJsfGVufDB8fDB8fHww',
    email: 'emma.adams@example.com',
    budget: '$3,200',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 11,
    name: 'Adams Jamiu',
    role: 'Jr. Dev',
    team: 'Development',
    status: 'active',
    age: '22',
    avatar:
      'https://media.istockphoto.com/id/172316242/photo/traditional-wear.jpg?s=612x612&w=0&k=20&c=yJJUq71Vrc83JZ7b4CH3DYTy3l7GuDvZ6VfTT4NCT6M=',
    email: 'brandon.stevens@example.com',
    budget: '$1,000',
    timeline: 'overdue',
    priority: 'low',
    lastReply: '11/02/2024',
    ticketSub: 'laptop',
    ticketID: 'tik1223',
  },
  {
    id: 12,
    name: 'Tolarin Alimat',
    role: 'P. Manager',
    team: 'Product',
    status: 'paused',
    age: '28',
    avatar:
      'https://images.unsplash.com/photo-1530785602389-07594beb8b73?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bmlnZXJpYW4lMjBnaXJsfGVufDB8fDB8fHww',
    email: 'megan.richards@example.com',
    budget: '$4,200',
    timeline: 'overdue',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'high',
    lastReply: '11/02/2024',
  },
  {
    id: 13,
    name: 'Alimat Jamiu',
    role: 'S. Manager',
    team: 'Security',
    status: 'active',
    age: '37',
    avatar:
      'https://images.unsplash.com/photo-1581941894991-b7f75a66b7bf?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fG5pZ2VyaWFuJTIwZ2lybHxlbnwwfHwwfHx8MA%3D%3D',
    email: 'oliver.scott@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 14,
    name: 'Grace Osik',
    role: 'M. Specialist',
    team: 'Marketing',
    status: 'active',
    age: '30',
    avatar:
      'https://images.unsplash.com/photo-1644152993066-9b9ee687930d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fG5pZ2VyaWFuJTIwZ2lybHxlbnwwfHwwfHx8MA%3D%3D',
    email: 'grace.allen@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 15,
    name: 'Osik John',
    role: 'IT Specialist',
    team: 'I. Technology',
    status: 'paused',
    age: '31',
    avatar:
      'https://media.istockphoto.com/id/639465722/photo/close-up-portrait-of-serious-man.jpg?s=612x612&w=0&k=20&c=sphg7Qz0B0ek92jjEHkcMhbiY4jrEy9rVo3s_5_F6Z8=',
    email: 'noah.carter@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'rent',
    priority: 'high',
    lastReply: '11/02/2024',
  },
  {
    id: 16,
    name: 'Oshomo Stpeve',
    role: 'Manager',
    team: 'Sales',
    status: 'active',
    age: '29',
    avatar:
      'https://media.istockphoto.com/id/172316242/photo/traditional-wear.jpg?s=612x612&w=0&k=20&c=yJJUq71Vrc83JZ7b4CH3DYTy3l7GuDvZ6VfTT4NCT6M=',
    email: 'ava.perez@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 17,
    name: 'Alakwe Johnson',
    role: 'Data Analyst',
    team: 'Analysis',
    status: 'active',
    age: '28',
    avatar:
      'https://media.istockphoto.com/id/1473209941/video/4k-video-footage-of-an-attractive-young-businessman-alone-on-the-street-during-the-day-stock.jpg?s=640x640&k=20&c=rxtHGv4OWOqhU5HrP3zh_uIaWgmlnPZHBWtZzheAzmE=',
    email: 'liam.johnson@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 18,
    name: 'Oshiogwe Taylor',
    role: 'QA Analyst',
    team: 'Testing',
    status: 'active',
    age: '27',
    avatar:
      'https://media.istockphoto.com/id/170617173/photo/confident-african-man.jpg?s=612x612&w=0&k=20&c=z70QyyDs34qV5dyUi-aGpVrHYamd259LFU_3NQXBFFo=',
    email: 'sophia.taylor@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
  {
    id: 19,
    name: 'Osioke Mattew',
    role: 'Administrator',
    team: 'Information Technology',
    status: 'paused',
    age: '32',
    avatar:
      'https://media.istockphoto.com/id/920857258/photo/smiling-african-man.jpg?s=612x612&w=0&k=20&c=YyU7detBrln3qm2w83xT3Dstrn6vrkhclHeWYYuZfmQ=',
    email: 'lucas.harris@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'food',
    priority: 'high',
    lastReply: '11/02/2024',
  },
  {
    id: 20,
    name: 'Ojior Dossuu',
    role: 'Coordinator',
    team: 'Operations',
    status: 'active',
    age: '26',
    avatar:
      'https://media.istockphoto.com/id/1729889021/photo/happy-african-american-man-looking-at-the-camera-portrait-picture.jpg?s=612x612&w=0&k=20&c=4eAAM2hxKVqCVD5mXcDo_nV_iu4zdAbJLhpLyH7D4RI=',
    email: 'mia.robinson@example.com',
    timeline: 'paid',
    ticketID: 'tik1223',
    ticketSub: 'laptop',
    priority: 'low',
    lastReply: '11/02/2024',
  },
]

const priority = [
  { label: 'Low', value: 'low' },
  { label: 'High', value: 'high' },
  { label: 'Medium', value: 'medium' },
]

const assignStaffs = [
  { label: 'John Femi', value: 'john femi' },
  { label: 'Ola Wisdom', value: 'ola wisdom' },
  { label: 'Twaio', value: 'twaio' },
]
const clients = [
  { label: 'Clan Africa', value: 'clan africa' },
  { label: 'Statisense', value: 'statisense' },
]

export { columns, users, statusOptions, priority, assignStaffs, clients }
