export const orders=[
{
img:'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/15/8198142/1.jpg?7735',
name:'C03 Unisex Designer Baseball Face cap-Black',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦5,000.00',
order_date:'On Friday, 01-03',
delivered_date:'On Monday, 04-03',
status:'delivered',
},
{
img:'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/01/6267662/1.jpg?3165',
name:'4 In 1 Ladies Handbags PU Leather Bucket Bags',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦13,059.00',
order_date:'On Friday, 01-03',
delivered_date:'On Monday, 04-03',
status:'delivered',
},
{
img:'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/25/2196612/1.jpg?6851',
name:'2Black Darkening & Anti-dandruff Unisex Hair Cream(80g)',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦1,500.00',
order_date:'On Friday, 01-03',
delivered_date:'On Monday, 04-03',
status:'delivered',
},
{
img:'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/67/5982502/1.jpg?2080',
name:'Midea 43 Litres Refrigerator (HS-65L) - Silver',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦148,915.00',
order_date:'On Friday, 01-03',
cancelled_date:'On Saturday, 02-03',
status:'unsuccessful_payment',
},
{
img:'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/45/6127391/1.jpg?2977',
name:'Oraimo Watch 2 GPS Function Football Heatmap Smart Watch With 133 Training Modes',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦40,500.00',
order_date:'On Friday, 01-03',
cancelled_date:'On Saturday, 02-03',
status:'unsuccessful_payment',
},
{
img:'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/77/130389/1.jpg?0674',
name:'Kiki New Gain Professional Rechargeable Hair Clipper - NG-777',
description:`The Air Force 1's distinctive design includes a chunky silhouette, a high-top ankle, and a prominent midsole with the visible Air cushioning unit. Over the years, the shoe has transcended its basketball roots to become a fashion staple,`,
order_no:'1576166392',
price:'₦16,740.00',
order_date:'On Friday, 01-03',
cancelled_date:'On Saturday, 02-03',
status:'unsuccessful_payment',
},
]