export const latestNews=[
{
head_line:'Oyebanji Lauds Tinubu For Release Of Kidnapped Ekiti School Children',
image_src:'https://cdn.punchng.com/wp-content/uploads/2023/11/06090148/Bola-Tinubu-3.jpg',
details:'The Governor of Ekiti State, Mr Biodun Oyebanji, has hinged the release of the kidnapped pupils and teachers of Apostolic Faith Nursery and Primary School, Emure Ekiti on the support of President Bola Tinubu, the security agencies, and Ekiti people in general. The children and their teachers, who were kidnapped on Monday, were released in the early hours of Sunday. However, the driver of the school bus was killed in the custody of the kidnappers. Oyebanji, in a statement by his Special Adviser on Media, Yinka Oyebode, while congratulating the children and their families, thanked President Tinubu “for giving specific directives that put the search and rescue mission on top gear. Oyebode stated that the governor also “thanked the security agencies for their collaborative efforts during the search for the students, just as he extended appreciation to Ekitikete home and abroad for their support during the security situation experienced last week. “He also thanks members of the Ekiti State Caucus in the National Assembly and members of the state House of Assembly for their support, saying, ‘And more importantly, we thank God for everything’”. The governor, however, restated his administration’s determination to stamp out crime and criminality from the state by making the environment unbearable for criminals operating under whatever guise. Oyebanji, who reiterated that the killers of the two Ekiti obas would be fished out and made to face the maximum weight of the law, urged people of the state to remain vigilant and report any suspicious movement in their communities to the authorities.',
category:'Politics',
date:'4th February 2024',
time_of_read:'10 mins read',
},
{
head_line:'82-Year-Old Nangolo Mbumba Sworn In As Fourth Namibian President After Geingob’s Death',
image_src:'https://saharareporters.com/sites/default/files/styles/focal_point_1300x650/public/2024-02/download%20%2847%29.jpg?h=44faf436&itok=ncJEh1Lh',
details:"Eighty-two-year-old Dr. Nangolo Mbumba has been sworn in as the fourth President. Mbumba is Namibia’s former Vice President and has held the position since 2018. He was sworn in on Sunday by Chief Justice Peter Shivute in Windhoek, the country’s capital. Born on August 15, 1941, Mbumba is a member of the South West Africa People's Organization (SWAPO). He headed several Namibian ministries: Agriculture, Water and Rural Development (1993–1996), Finance (1996–2003), Information and Broadcasting (2003–2005) Education (2005–2010) and Safety and Security (2010–2012). From 2012 to 2017, he was the secretary-general of SWAPO. SaharaReporters earlier reported that the Namibian government had announced that President Geingob died on Sunday, February 4, 2024, at Lady Pohamba Hospital, a private hospital in Windhoek. He died at 82 weeks after he was diagnosed with cancer. The former Acting President, Mbumba, who announced the death of the late President on Sunday, said the nation had lost its pillar and the chief architect of its constitution. According to him, the President died despite the best efforts of his medical team to ensure his recovery. Mbumba said the President’s wife, Monica Geingos and his children were by his side when he passed on. In his condolence message on Sunday, Nigeria’s President, Bola Tinubu described the late Namibian President as a veteran in the struggle for democracy, a proponent of good governance and an advocate for economic, social and political solidarity among African peoples. President Tinubu wrote, “On behalf of the government and people of Nigeria, I extend our deepest condolences to the government and people of Namibia over the passing of His Excellency, President Hage Geingob. “I mourn the painful loss of a veteran in the struggle for democracy, a proponent of good governance, and an advocate for economic, social, and political solidarity among African peoples. “This tragedy comes at a time when Africa is in dire need of more visionary leaders who believe in our common destiny and who can strengthen the bonds across our borders and spread the tendrils of cooperation in all fields of human endeavour. “As Namibia mourns, I want to assure the Republic that my thoughts and prayers, and indeed those of all Nigerians, are with you.”",
category:'Politics',
date:'4th February 2024',
time_of_read:'10 mins read',
},
{
head_line:'Bye-elections in Surulere: Laguda replaces Femi Gbajabiamila',
image_src:'https://dailypost.ng/wp-content/uploads/2024/02/Fuad-Laguda.jpg',
details:'The candidate of the All Progressives Congress, APC, for the bye-election in Surulere Federal Constituency I, Lagos, Fuad Laguda has been declared winner of the polls. The Independent National Electoral Commission, INEC declared him winner of the Saturday election after garnering 11,203 votes. While declaring the results, the Returning Officer for the bye-election, Prof Simeon Adebayo, said the APC candidate scored the highest votes. Laguda defeated his main challengers, Adeola Adebanjo of the Labour Party and Jerry Afemighie of the Peoples Democratic Party. DAILY POST reports that the seat was declared vacant following Femi Gbajabiamila‘s resignation to become the Chief of Staff to President Bola Tinubu.',
category:'Politics',
date:'14th January 2024',
time_of_read:'6 mins read',
},
]
export const previousNews=[
{
head_line:'Majority of Bromley children get first-choice secondary school offer',
image_src:'https://www.newsinbeckenham.co.uk/wp-content/uploads/2021/03/School-Stock-777x437.jpg',
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Education',
date:'8th January 2024',
time_of_read:'4 mins read',
},
{
head_line:'Arsenal vs Liverpool 3-1: Premier League football – as it happened',
image_src:"https://pbs.twimg.com/media/GFg16mNXwAAtT-P?format=jpg&name=small",
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Sport',
date:'12th December 2023',
time_of_read:'5 mins read',
},
{
head_line:'Should Bitcoin still be treated as a reliable long-term investment?',
image_src:'https://fintechweekly.s3.amazonaws.com/article/350/Templatemaster_Article_Images_MARA_5_.png',
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Fintech',
date:'2rd February 2024',
time_of_read:'8 mins read',
},
{
head_line:'Majority of Bromley children get first-choice secondary school offer',
image_src:'https://www.newsinbeckenham.co.uk/wp-content/uploads/2021/03/School-Stock-777x437.jpg',
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Education',
date:'10th January 2024',
time_of_read:'7 mins read',
},
{
head_line:'Arsenal vs Liverpool 3-1: Premier League football – as it happened',
image_src:"https://pbs.twimg.com/media/GFg16mNXwAAtT-P?format=jpg&name=small",
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Sport',
date:'4th February 2024',
time_of_read:'10 mins read',
},
{
head_line:'Should Bitcoin still be treated as a reliable long-term investment?',
image_src:'https://fintechweekly.s3.amazonaws.com/article/350/Templatemaster_Article_Images_MARA_5_.png',
details:'  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, similique. Magnam, nostrum necessitatibus incidunt deserunt esse aperiam corrupti, illo recusandae at iusto mollitia est facilis, labore dicta totam placeat! Vero Ducimus, dignissimos harum dolores architecto atque quod minus inventore eos, consequatur natus magnam beatae vitae et nisi fugiat illum quia ullam voluptate, rerum voluptates. Deserunt voluptatum consequuntur fuga repellat qui. Officia error cumque quaerat rem ut repudiandae cum, omnis voluptatem ab, nobis ipsa deserunt sapiente at modi beatae perspiciatis? Aliquid facere ipsam voluptates ipsa nostrum rem ab molestiae quos odit? Voluptatibus ipsa quae accusantium corporis voluptate culpa asperiores quis, temporibus modi voluptates soluta error quod, porro optio voluptas harum aliquam numquam eos? Aut nihil iusto aspernatur illo! Quo, quod libero. Ipsum consequatur doloribus veniam totam molestiae impedit unde debitis perferendis. In, odio autem molestias explicabo cum voluptatibus nulla voluptate obcaecati, nesciunt labore, quae asperiores beatae quibusdam dignissimos eligendi optio a!',
category:'Fintech',
date:'4th February 2024',
time_of_read:'10 mins read',
},
]