const columns = [
  { name: 'ID', uid: 'id', sortable: true },
  { name: 'NAME', uid: 'name', sortable: true },
  { name: 'AGE', uid: 'age', sortable: true },
  { name: 'ROLE', uid: 'role', sortable: true },
  { name: 'TEAM', uid: 'team' },
  { name: 'EMAIL', uid: 'email' },
  { name: 'STATUS', uid: 'status', sortable: true },
  { name: 'COURSE', uid: 'course' },
  { name: 'COMPANY', uid: 'company' },
  { name: 'START DATE', uid: 'start date' },
  { name: 'END DATE', uid: 'end date' },
  { name: 'EMPLOYMENT TYPE', uid: 'EMPLOYMENT TYPE' },
  { name: 'AUDIT REMARK', uid: 'AUDIT REMARK' },
  { name: 'AUDITED BY', uid: 'AUDITED BY' },
  { name: 'APPROVED BY HR', uid: 'APPROVED BY HR' },
  { name: 'AUDIT STATUS', uid: 'AUDIT STATUS' },
  { name: 'HR STATUS', uid: 'HR STATUS' },
  { name: 'CREATED BY', uid: 'CREATED BY' },
  { name: 'DATE ADDED', uid: 'DATE ADDED' },
  { name: 'EMP. NO', uid: 'EMP. NO' },
  { name: 'ATTACHMENT', uid: 'attachment' },
  { name: 'ACTIONS', uid: 'actions' },
]

const statusOptions = [
  { name: 'Active', uid: 'active' },
  { name: 'Paused', uid: 'paused' },
  { name: 'Vacation', uid: 'vacation' },
]

const educationData = [
  {
    id: 1,
    schoolInitial: 'UI',
    course: 'Bachelor of Science in Computer Science',
    startDate: '2016-09-01',
    endDate: '2020-06-01',
    cgpa: 3.8,
    degreeType: 'Bachelor',
    degreeInitial: 'BSc',
    name: 'University of Ibadan',
    attachment: 'Bachelor_Transcript.pdf', // Add attachment field
  },
  {
    id: 2,
    schoolInitial: 'OAU',
    course: 'Master of Business Administration',
    startDate: '2020-09-01',
    endDate: '2022-06-01',
    cgpa: 4.0,
    degreeType: 'Master',
    degreeInitial: 'MBA',
    name: 'Obafemi Awolowo University',
    attachment: 'MBA_Diploma.pdf',
  },
  {
    id: 3,
    schoolInitial: 'MHS',
    startDate: '2012-09-01',
    endDate: '2015-06-01',
    degreeType: 'SSCE',
    degreeInitial: 'SSCE',
    name: 'Moshelen High School',
    attachment: 'SSCE_WEAC.pdf',
  },
  {
    id: 4,
    schoolInitial: 'MHS',
    startDate: '2009-09-01',
    endDate: '2012-06-01',
    degreeType: 'JSCE',
    degreeInitial: 'JSCE',
    name: 'Moshelen High School',
    attachment: 'JSCE_WEAC.pdf',
  },
  {
    id: 5,
    schoolInitial: 'GGI',
    startDate: '2003-09-01',
    endDate: '2009-06-01',
    degreeType: 'Primary School',
    degreeInitial: 'Primary SchoolT',
    name: 'Golden Gate International',
    attachment: 'Primary_School.pdf',
  },
  // Add more education data as needed
]

const users = [
  {
    id: 1,
    name: 'UI',
    role: 'CEO',
    team: 'Management',
    status: 'active',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
    company: 'clan Africa',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'Physiology',
    degree: 'Bsc',
    grade: 3.4,
  },
  {
    id: 2,
    name: 'FUTA',
    role: 'Tech Lead',
    team: 'Development',
    status: 'paused',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
    company: 'Farm fram',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'Biology',
    degree: 'Bsc.ED',
    grade: 3.4,
  },
  {
    id: 3,
    name: 'UNIZICE',
    role: 'Sr. Dev',
    team: 'Development',
    status: 'active',
    age: '22',
    // avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    avatar: 'UZ',
    email: 'jane.fisher@example.com',
    company: 'zuz stand',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'English',
    degree: 'Bsc',
    grade: 4.4,
  },
  {
    id: 4,
    name: 'Havowrd',
    role: 'C.M.',
    team: 'Marketing',
    status: 'vacation',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
    company: 'Africa done',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'Medcine',
    degree: 'Bsc',
    grade: 3.4,
  },
  {
    id: 5,
    name: 'Kristen Copper',
    role: 'S. Manager',
    team: 'Sales',
    status: 'active',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
    company: 'Access Bank',
    attachment: 'attachment',
    course: 'Plilantropist',
    degree: 'Bsc',
    grade: 3.4,
  },
  {
    id: 6,
    name: 'Brian Kim',
    role: 'P. Manager',
    team: 'Management',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'brian.kim@example.com',
    status: 'Active',
    company: ' Africa Debt',
    startdate: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'Maths',
    degree: 'Bsc.ED',
    grade: 3.4,
  },
  {
    id: 7,
    name: 'Michael Hunt',
    role: 'Designer',
    team: 'Design',
    status: 'paused',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
    email: 'michael.hunt@example.com',
    company: 'clan Tech',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
    course: 'Physiology',
    degree: 'Bsc',
    grade: 5.0,
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    role: 'HR Manager',
    team: 'HR',
    status: 'active',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
    email: 'samantha.brooks@example.com',
    company: 'clan Africa',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    attachment: 'attachment',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    role: 'F. Manager',
    team: 'Finance',
    status: 'vacation',
    age: '33',
    avatar: 'https://i.pravatar.cc/150?img=4',
    email: 'frank.harrison@example.com',
    start_date: '2020-01-01',
    end_date: '2020-01-01',
    company: 'zuz stand',
    attachment: 'attachment',
  },
  {
    id: 10,
    name: 'Emma Adams',
    role: 'Ops Manager',
    team: 'Operations',
    status: 'active',
    age: '35',
    avatar: 'https://i.pravatar.cc/150?img=5',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    role: 'Jr. Dev',
    team: 'Development',
    status: 'active',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?img=8',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    role: 'P. Manager',
    team: 'Product',
    status: 'paused',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=10',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    role: 'S. Manager',
    team: 'Security',
    status: 'active',
    age: '37',
    avatar: 'https://i.pravatar.cc/150?img=12',
    email: 'oliver.scott@example.com',
    company: 'zuz stand',
  },
  {
    id: 14,
    name: 'Grace Allen',
    role: 'M. Specialist',
    team: 'Marketing',
    status: 'active',
    age: '30',
    avatar: 'https://i.pravatar.cc/150?img=16',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    role: 'IT Specialist',
    team: 'I. Technology',
    status: 'paused',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?img=15',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    role: 'Manager',
    team: 'Sales',
    status: 'active',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?img=20',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    role: 'Data Analyst',
    team: 'Analysis',
    status: 'active',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=33',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    role: 'QA Analyst',
    team: 'Testing',
    status: 'active',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?img=29',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    role: 'Administrator',
    team: 'Information Technology',
    status: 'paused',
    age: '32',
    avatar: 'https://i.pravatar.cc/150?img=50',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    role: 'Coordinator',
    team: 'Operations',
    status: 'active',
    age: '26',
    avatar: 'https://i.pravatar.cc/150?img=45',
    email: 'mia.robinson@example.com',
  },
]

const certificationData = [
  {
    id: 1,
    name: 'Project Management 1',
    organization: 'Amazon Web Services',
    orgInitial: 'AWS',
    date: '2023-01-15',
    course: 'Project Management',
    startDate: '2022-12-01',
    endDate: '2023-01-01',
    certificateInitial: 'PM!',
    attachment: 'Project_managment.pdf',
  },
  {
    id: 2,
    name: 'Cloud Computing',
    organization: 'Amazon Web Services',
    orgInitial: 'AWS',
    date: '2023-05-20',
    course: 'Cyber Security',
    startDate: '2023-03-01',
    endDate: '2023-04-01',
    certificateInitial: 'C C',
    attachment: 'Cyber_security.pdf',
  },
  {
    id: 3,
    name: 'Solutions Expert',
    organization: 'Microsoft Certified Solutions Expert',
    orgInitial: 'MCSE',
    date: '2023-05-20',
    course: 'Solutions Expert Architect',
    startDate: '2023-05-01',
    endDate: '2023-08-01',
    certificateInitial: 'MCSE',
    attachment: 'MCSE.pdf',
  },
  // Add more certification objects as needed
]

export { columns, users, statusOptions, educationData, certificationData }
