
import { MdApproval , } from "react-icons/md";


export const tableData = [
    {
      _id: 1,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'rejected',
    },
    {
      _id: 2,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
     {
      _id: 3,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },
    {
      _id: 4,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
    {
      _id: 5,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },
     {
      _id: 6,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
        {
      _id: 7,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'rejected',
    },
    {
      _id: 8,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },
       {
      _id: 9,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
    {
      _id: 10,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },   
     {
      _id: 11,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
    {
      _id: 12,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },
       {
      _id: 13,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
     {
      _id: 14,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'rejected',
    },
      {
      _id: 15,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
     {
      _id: 16,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'rejected',
    },
    {
      _id: 17,
      name: "Olayinka Gabriel",
      employment_type: "Full time",
      sent_on: '2024-09-02',
      responded_on: '2024-09-14',
      location: 'Abule-egba',
      approved_by: "Adegbile Johnson",
      status: 'approved',
    },
     {
      _id: 18,
      name: "Olayinka Gabriel",
      employment_type: "Contract",
      sent_on: '2024-09-02',
      responded_on: '',
      location: 'Abule-egba',
      approved_by: " ",
      status: 'pending',
    },
    
  ];

export const columns = [
  {name: "id", uid: "_id", sortable: true},
  {name: "name", uid: "name", sortable: true},
  {name: "employment type", uid: "employment_type", sortable: true},
  {name: "sent on", uid: "sent_on", sortable: true},
  {name: "responded on", uid: "responded_on", sortable: true},
  // {name: "location", uid: "location", sortable: true},
  {name: "approved by hr", uid: "approved_by", sortable: true},
  {name: "status", uid: "status", sortable: true},
  {name: "Actions", uid: "actions", sortable: true},
];

export const status = [
  { name: "pending", uid: "pending" },
  { name: "approved", uid: "approved" },
  { name: "rejected", uid: "rejected" },
];

export const statusColor = {
  pending: "warning",
  approved: "success",
  rejected: "danger",
};

export const tableHeader = [
  "name",
  "employment_type",
  "sent_on",
  "responded_on",
  // "location",
  "approved_by",
  "status",
  "actions"
];


export const approvalHistory = [
  {
    type: "Approval Request",
    key: "approval_request",
    no_of_approvals: 6,
    icon: MdApproval  ,
    b_color: "bg-amber-100",
    t_color: "text-amber-500",
  },
  {
    type: "Rejected Approvals",
    key: "rejected_request",
    no_of_approvals: 4,
    icon: MdApproval  ,
    b_color: "bg-red-100",
    t_color: "text-red-500",
  },
  {
    type: "Approved Approvals",
    key: "approved_request",
    no_of_approvals: 8,
    icon: MdApproval  ,
    b_color: "bg-green-100",
    t_color: "text-green-500",
  },
  {
    type: "Total Approvals",
    key: "_request",
    no_of_approvals: 18,
    icon: MdApproval  ,
    b_color: "bg-purple-100",
    t_color: "text-purple-500",
  },
];
