export const trainingData = [{
    "_id": 1,
    "creator": "Nikola Benoey",
    "directorate": "Professional Development",
    "title": "Web Development Fundamentals",
    "type": "Regional",
    "staff": 21,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 5,
    "venue": "Göteborg",
    "fee": "500",
    "category": "Completed",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 2,
    "creator": "Theresa Kittow",
    "directorate": "Professional Development",
    "title": "Graphic Design Principles",
    "type": "National",
    "staff": 14,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 2,
    "venue": "Phuket",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 3,
    "creator": "Kent Godlee",
    "directorate": "Professional Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "International",
    "staff": 26,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Ar Ruways",
    "fee": "000",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 4,
    "creator": "Farrell Thebeau",
    "directorate": "Training Operations",
    "title": "Project Management Basics",
    "type": "Local",
    "staff": 42,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Montgomery",
    "fee": "000",
    "category": "Completed",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 5,
    "creator": "Harriott McCarroll",
    "directorate": "Training Operations",
    "title": "Cloud Computing Fundamentals",
    "type": "National",
    "staff": 50,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Villeneuve-d'Ascq",
    "fee": "000",
    "category": "Upcoming",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 6,
    "creator": "Darwin Ruspine",
    "directorate": "Professional Development",
    "title": "Graphic Design Principles",
    "type": "International",
    "staff": 35,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Kurumkan",
    "fee": "500",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 7,
    "creator": "Mischa Rojel",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "National",
    "staff": 45,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Jieheshi",
    "fee": "000",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 8,
    "creator": "Nobe Haston",
    "directorate": "Talent Development",
    "title": "Introduction to Python Programming",
    "type": "International",
    "staff": 35,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Tinumpuk",
    "fee": "000",
    "category": "Upcoming",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 9,
    "creator": "Kerwin Scarre",
    "directorate": "Training Operations",
    "title": "Cloud Computing Fundamentals",
    "type": "Local",
    "staff": 30,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Khong",
    "fee": "400",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 10,
    "creator": "Abigale Mountney",
    "directorate": "Professional Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "Local",
    "staff": 16,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 15,
    "venue": "Dama",
    "fee": "000",
    "category": "Completed",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 11,
    "creator": "Kristel Boggish",
    "directorate": "Learning and Development",
    "title": "Mobile App Development",
    "type": "International",
    "staff": 41,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 8,
    "venue": "Songgai",
    "fee": "000",
    "category": "Upcoming",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 12,
    "creator": "Bill Macknish",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "Regional",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Mashi",
    "fee": "000",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 13,
    "creator": "Rhody Horburgh",
    "directorate": "Talent Development",
    "title": "Machine Learning Fundamentals",
    "type": "International",
    "staff": 17,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 17,
    "venue": "Baltimore",
    "fee": "500",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 14,
    "creator": "Karry Marsham",
    "directorate": "Talent Development",
    "title": "Mobile App Development",
    "type": "National",
    "staff": 32,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 4,
    "venue": "Pontian",
    "fee": "400",
    "category": "Upcoming",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 15,
    "creator": "Sharla Ivell",
    "directorate": "Talent Development",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 50,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 0,
    "venue": "Fengkou",
    "fee": "000",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 16,
    "creator": "Dayna Cumpsty",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "Local",
    "staff": 28,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 13,
    "venue": "Taunan",
    "fee": "100",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 17,
    "creator": "Leonanie Dalbey",
    "directorate": "Talent Development",
    "title": "Introduction to Python Programming",
    "type": "Regional",
    "staff": 2,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 0,
    "venue": "Melbourne",
    "fee": "500",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 18,
    "creator": "Zackariah Potkin",
    "directorate": "Training Operations",
    "title": "Web Development Fundamentals",
    "type": "Regional",
    "staff": 49,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 3,
    "venue": "Tanjungkerta",
    "fee": "300",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 19,
    "creator": "Camila Kleinert",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "Local",
    "staff": 16,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Cerrito",
    "fee": "200",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 20,
    "creator": "Meagan Cubberley",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "International",
    "staff": 30,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Chon Buri",
    "fee": "500",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 21,
    "creator": "Regan End",
    "directorate": "Training Operations",
    "title": "Cybersecurity Essentials",
    "type": "National",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Vredefort",
    "fee": "000",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 22,
    "creator": "Norbert Baggalley",
    "directorate": "Training Operations",
    "title": "Cloud Computing Fundamentals",
    "type": "International",
    "staff": 13,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 18,
    "venue": "Haurpanggung",
    "fee": "400",
    "category": "Upcoming",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 23,
    "creator": "Jedd Sewley",
    "directorate": "Talent Development",
    "title": "Project Management Basics",
    "type": "International",
    "staff": 44,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "San Isidro",
    "fee": "000",
    "category": "Completed",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 24,
    "creator": "Kitty Charlon",
    "directorate": "Talent Development",
    "title": "Introduction to Python Programming",
    "type": "National",
    "staff": 37,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Bezerros",
    "fee": "200",
    "category": "Completed",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 25,
    "creator": "Keelby Huitson",
    "directorate": "Training Operations",
    "title": "Mobile App Development",
    "type": "Regional",
    "staff": 2,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 8,
    "venue": "Xinyu",
    "fee": "400",
    "category": "Completed",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 26,
    "creator": "Damien Alam",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "Local",
    "staff": 5,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 3,
    "venue": "Manggu",
    "fee": "200",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 27,
    "creator": "Edin Sandom",
    "directorate": "Talent Development",
    "title": "Mobile App Development",
    "type": "Regional",
    "staff": 9,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 4,
    "venue": "Лабуништа",
    "fee": "100",
    "category": "Pending",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 28,
    "creator": "Angelique Mingaye",
    "directorate": "Learning and Development",
    "title": "Digital Marketing Strategies",
    "type": "Regional",
    "staff": 40,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 6,
    "venue": "Ménaka",
    "fee": "000",
    "category": "Pending",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 29,
    "creator": "Hermann Lippiatt",
    "directorate": "Professional Development",
    "title": "Machine Learning Fundamentals",
    "type": "Regional",
    "staff": 44,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 18,
    "venue": "Jiujianfang",
    "fee": "400",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 30,
    "creator": "Emlyn Arlow",
    "directorate": "Professional Development",
    "title": "Machine Learning Fundamentals",
    "type": "Regional",
    "staff": 18,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Lodoyo",
    "fee": "000",
    "category": "Upcoming",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 31,
    "creator": "Nert Rattenbury",
    "directorate": "Employee Training",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 2,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Guiglo",
    "fee": "400",
    "category": "Cancelled",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 32,
    "creator": "Aguste Ludgate",
    "directorate": "Professional Development",
    "title": "Mobile App Development",
    "type": "Local",
    "staff": 38,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 18,
    "venue": "Krajan Sumurtawang",
    "fee": "100",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 33,
    "creator": "Penrod Hully",
    "directorate": "Employee Training",
    "title": "Mobile App Development",
    "type": "Regional",
    "staff": 43,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 20,
    "venue": "Glondong",
    "fee": "000",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 34,
    "creator": "Yoshiko Fellowes",
    "directorate": "Professional Development",
    "title": "Web Development Fundamentals",
    "type": "Local",
    "staff": 17,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 2,
    "venue": "Bandhagen",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 35,
    "creator": "Mile McTurk",
    "directorate": "Training Operations",
    "title": "Cybersecurity Essentials",
    "type": "Local",
    "staff": 36,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 4,
    "venue": "Kibiti",
    "fee": "000",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 36,
    "creator": "Hilton Kybird",
    "directorate": "Professional Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "Regional",
    "staff": 13,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Metz",
    "fee": "000",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 37,
    "creator": "Sibilla Alu",
    "directorate": "Talent Development",
    "title": "Machine Learning Fundamentals",
    "type": "Local",
    "staff": 23,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 4,
    "venue": "Ajaccio",
    "fee": "000",
    "category": "Upcoming",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 38,
    "creator": "Olenolin Heaker",
    "directorate": "Talent Development",
    "title": "Cybersecurity Essentials",
    "type": "Regional",
    "staff": 17,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Hod HaSharon",
    "fee": "300",
    "category": "Completed",
    "description": "Learn how to code in Python"
  }, {
    "_id": 39,
    "creator": "Viv Beamont",
    "directorate": "Professional Development",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 42,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 8,
    "venue": "Cojutepeque",
    "fee": "000",
    "category": "Cancelled",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 40,
    "creator": "Gusella Fawthrop",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "National",
    "staff": 48,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Beyla",
    "fee": "000",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 41,
    "creator": "Nils Kopacek",
    "directorate": "Learning and Development",
    "title": "Cloud Computing Fundamentals",
    "type": "International",
    "staff": 24,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 15,
    "venue": "Pangkalan",
    "fee": "500",
    "category": "Pending",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 42,
    "creator": "Dionne Harbach",
    "directorate": "Training Operations",
    "title": "Digital Marketing Strategies",
    "type": "Local",
    "staff": 21,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 17,
    "venue": "Los Frentones",
    "fee": "200",
    "category": "Cancelled",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 43,
    "creator": "Matthus Copnall",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "International",
    "staff": 30,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Chengguan",
    "fee": "300",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 44,
    "creator": "Liv Bourdas",
    "directorate": "Employee Training",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 49,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Road Town",
    "fee": "000",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 45,
    "creator": "Mirabel Horsted",
    "directorate": "Training Operations",
    "title": "Cybersecurity Essentials",
    "type": "Regional",
    "staff": 20,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Dầu Tiếng",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 46,
    "creator": "Neddie Derry",
    "directorate": "Employee Training",
    "title": "Machine Learning Fundamentals",
    "type": "Local",
    "staff": 4,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Shuanggang",
    "fee": "200",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 47,
    "creator": "Bank Hugnin",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 16,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 6,
    "venue": "Karema",
    "fee": "000",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 48,
    "creator": "Korry Bemwell",
    "directorate": "Employee Training",
    "title": "Advanced Data Analysis Techniques",
    "type": "National",
    "staff": 14,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 20,
    "venue": "Kekeran",
    "fee": "000",
    "category": "Upcoming",
    "description": "Learn how to code in Python"
  }, {
    "_id": 49,
    "creator": "Kaiser Slot",
    "directorate": "Learning and Development",
    "title": "Digital Marketing Strategies",
    "type": "Local",
    "staff": 41,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Hyattsville",
    "fee": "500",
    "category": "Completed",
    "description": "Learn how to code in Python"
  }, {
    "_id": 50,
    "creator": "Jeddy Hinge",
    "directorate": "Talent Development",
    "title": "Digital Marketing Strategies",
    "type": "National",
    "staff": 49,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Zhaiwu",
    "fee": "300",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 51,
    "creator": "Janelle Zoellner",
    "directorate": "Professional Development",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 34,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 15,
    "venue": "Sułkowice",
    "fee": "200",
    "category": "Pending",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 52,
    "creator": "Laurene Spini",
    "directorate": "Professional Development",
    "title": "Graphic Design Principles",
    "type": "National",
    "staff": 17,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Urukh",
    "fee": "200",
    "category": "Completed",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 53,
    "creator": "Penelopa Bayfield",
    "directorate": "Training Operations",
    "title": "Introduction to Python Programming",
    "type": "International",
    "staff": 33,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 13,
    "venue": "Zapatero",
    "fee": "000",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 54,
    "creator": "Jerrold Blooman",
    "directorate": "Training Operations",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 34,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Halle",
    "fee": "100",
    "category": "Pending",
    "description": "Learn how to code in Python"
  }, {
    "_id": 55,
    "creator": "Cheryl Yepiskov",
    "directorate": "Talent Development",
    "title": "Project Management Basics",
    "type": "Local",
    "staff": 23,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Yelets",
    "fee": "300",
    "category": "Completed",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 56,
    "creator": "Joyan Yoskowitz",
    "directorate": "Training Operations",
    "title": "Machine Learning Fundamentals",
    "type": "International",
    "staff": 40,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Vrbovec",
    "fee": "500",
    "category": "Cancelled",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 57,
    "creator": "Cad Ashburne",
    "directorate": "Professional Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "National",
    "staff": 4,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 17,
    "venue": "Pimenta Bueno",
    "fee": "000",
    "category": "Cancelled",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 58,
    "creator": "Gay Pountney",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 49,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 0,
    "venue": "Kongwan",
    "fee": "000",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 59,
    "creator": "Celinda Chrestien",
    "directorate": "Talent Development",
    "title": "Mobile App Development",
    "type": "International",
    "staff": 12,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Shchastya",
    "fee": "300",
    "category": "Pending",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 60,
    "creator": "Mikey Speachley",
    "directorate": "Employee Training",
    "title": "Digital Marketing Strategies",
    "type": "Local",
    "staff": 20,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 12,
    "venue": "Solo",
    "fee": "000",
    "category": "Completed",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 61,
    "creator": "Aile Baxster",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "National",
    "staff": 8,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 13,
    "venue": "Tilmi",
    "fee": "100",
    "category": "Completed",
    "description": "Learn how to code in Python"
  }, {
    "_id": 62,
    "creator": "Cherida Foskett",
    "directorate": "Talent Development",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 29,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 16,
    "venue": "Petaling Jaya",
    "fee": "000",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 63,
    "creator": "Fania Cornuau",
    "directorate": "Professional Development",
    "title": "Mobile App Development",
    "type": "National",
    "staff": 46,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Duut",
    "fee": "200",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 64,
    "creator": "Spence Bigglestone",
    "directorate": "Training Operations",
    "title": "Cloud Computing Fundamentals",
    "type": "Local",
    "staff": 26,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Deauville",
    "fee": "400",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 65,
    "creator": "Ilyssa Parchment",
    "directorate": "Employee Training",
    "title": "Cloud Computing Fundamentals",
    "type": "International",
    "staff": 8,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 2,
    "venue": "Mori",
    "fee": "000",
    "category": "Upcoming",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 66,
    "creator": "Neysa Seamarke",
    "directorate": "Learning and Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "Local",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Floreşti",
    "fee": "000",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 67,
    "creator": "Marylou Padbury",
    "directorate": "Learning and Development",
    "title": "Introduction to Python Programming",
    "type": "Local",
    "staff": 34,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "El Hermel",
    "fee": "100",
    "category": "Pending",
    "description": "Learn how to code in Python"
  }, {
    "_id": 68,
    "creator": "Kim Ogbourne",
    "directorate": "Training Operations",
    "title": "Graphic Design Principles",
    "type": "International",
    "staff": 0,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Acul du Nord",
    "fee": "100",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 69,
    "creator": "Daniel Braikenridge",
    "directorate": "Training Operations",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 11,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 5,
    "venue": "Egindiköl",
    "fee": "000",
    "category": "Upcoming",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 70,
    "creator": "Ajay Glanvill",
    "directorate": "Professional Development",
    "title": "Cloud Computing Fundamentals",
    "type": "Local",
    "staff": 40,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 16,
    "venue": "Waco",
    "fee": "400",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 71,
    "creator": "Donni Loan",
    "directorate": "Employee Training",
    "title": "Cybersecurity Essentials",
    "type": "Local",
    "staff": 37,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 2,
    "venue": "Lantian",
    "fee": "500",
    "category": "Upcoming",
    "description": "Learn how to code in Python"
  }, {
    "_id": 72,
    "creator": "Clive Organ",
    "directorate": "Talent Development",
    "title": "Mobile App Development",
    "type": "International",
    "staff": 18,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 17,
    "venue": "Dashiqiao",
    "fee": "100",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 73,
    "creator": "Tabatha Brabant",
    "directorate": "Learning and Development",
    "title": "Web Development Fundamentals",
    "type": "Local",
    "staff": 11,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 16,
    "venue": "Emiliano Zapata",
    "fee": "200",
    "category": "Upcoming",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 74,
    "creator": "Evered Farrimond",
    "directorate": "Professional Development",
    "title": "Introduction to Python Programming",
    "type": "Local",
    "staff": 0,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 6,
    "venue": "Sydney",
    "fee": "000",
    "category": "Completed",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 75,
    "creator": "Donielle Bernollet",
    "directorate": "Professional Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "Regional",
    "staff": 32,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 16,
    "venue": "Leonidovo",
    "fee": "000",
    "category": "Pending",
    "description": "Learn how to code in Python"
  }, {
    "_id": 76,
    "creator": "Caril Nend",
    "directorate": "Training Operations",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 1,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 13,
    "venue": "Xianlong",
    "fee": "100",
    "category": "Cancelled",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 77,
    "creator": "Johnathan Mallindine",
    "directorate": "Training Operations",
    "title": "Mobile App Development",
    "type": "International",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Banjar Pangkungtibah Selatan",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 78,
    "creator": "Dun Petrulis",
    "directorate": "Learning and Development",
    "title": "Cybersecurity Essentials",
    "type": "Local",
    "staff": 34,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Vaughan",
    "fee": "000",
    "category": "Completed",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 79,
    "creator": "Sondra Cringle",
    "directorate": "Employee Training",
    "title": "Web Development Fundamentals",
    "type": "National",
    "staff": 39,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 2,
    "venue": "Huanglong",
    "fee": "000",
    "category": "Completed",
    "description": "Learn how to code in Python"
  }, {
    "_id": 80,
    "creator": "Kassey Caldroni",
    "directorate": "Employee Training",
    "title": "Graphic Design Principles",
    "type": "Regional",
    "staff": 36,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 12,
    "venue": "Gaopai",
    "fee": "000",
    "category": "Cancelled",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 81,
    "creator": "Lennard Edgeson",
    "directorate": "Learning and Development",
    "title": "Project Management Basics",
    "type": "National",
    "staff": 24,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 12,
    "venue": "Duoxiang",
    "fee": "500",
    "category": "Upcoming",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 82,
    "creator": "Reese Spadoni",
    "directorate": "Professional Development",
    "title": "Cybersecurity Essentials",
    "type": "National",
    "staff": 21,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Caen",
    "fee": "100",
    "category": "Pending",
    "description": "Learn how to code in Python"
  }, {
    "_id": 83,
    "creator": "Eugene Welch",
    "directorate": "Employee Training",
    "title": "Advanced Data Analysis Techniques",
    "type": "Local",
    "staff": 46,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 3,
    "venue": "Hevlín",
    "fee": "100",
    "category": "Completed",
    "description": "Learn how to code in Python"
  }, {
    "_id": 84,
    "creator": "Franciska Muslim",
    "directorate": "Talent Development",
    "title": "Mobile App Development",
    "type": "National",
    "staff": 27,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 10,
    "venue": "Guanyang",
    "fee": "000",
    "category": "Upcoming",
    "description": "Discover the secrets of successful entrepreneurship"
  }, {
    "_id": 85,
    "creator": "Ettie Hunting",
    "directorate": "Talent Development",
    "title": "Advanced Data Analysis Techniques",
    "type": "National",
    "staff": 45,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 14,
    "venue": "Askainen",
    "fee": "100",
    "category": "Pending",
    "description": "Learn how to code in Python"
  }, {
    "_id": 86,
    "creator": "Hendrick Ivanikov",
    "directorate": "Training Operations",
    "title": "Digital Marketing Strategies",
    "type": "Regional",
    "staff": 27,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Juzhen",
    "fee": "000",
    "category": "Cancelled",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 87,
    "creator": "Purcell Barock",
    "directorate": "Training Operations",
    "title": "Project Management Basics",
    "type": "Local",
    "staff": 42,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 18,
    "venue": "Houjiachuan",
    "fee": "000",
    "category": "Completed",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 88,
    "creator": "Bethanne Dray",
    "directorate": "Learning and Development",
    "title": "Graphic Design Principles",
    "type": "International",
    "staff": 24,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Sumberkertokrajan",
    "fee": "200",
    "category": "Pending",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 89,
    "creator": "Hi Raffeorty",
    "directorate": "Talent Development",
    "title": "Introduction to Python Programming",
    "type": "Regional",
    "staff": 30,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 9,
    "venue": "Penedono",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 90,
    "creator": "Dagmar Chellingworth",
    "directorate": "Employee Training",
    "title": "Digital Marketing Strategies",
    "type": "National",
    "staff": 43,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 7,
    "venue": "Bahui",
    "fee": "400",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 91,
    "creator": "Aila Capener",
    "directorate": "Professional Development",
    "title": "Web Development Fundamentals",
    "type": "Regional",
    "staff": 24,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 19,
    "venue": "Pedrulheira",
    "fee": "300",
    "category": "Upcoming",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 92,
    "creator": "Lilah Cullrford",
    "directorate": "Training Operations",
    "title": "Introduction to Python Programming",
    "type": "Local",
    "staff": 28,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 16,
    "venue": "Fubei",
    "fee": "500",
    "category": "Upcoming",
    "description": "Learn how to code in Python"
  }, {
    "_id": 93,
    "creator": "Templeton Sauvage",
    "directorate": "Employee Training",
    "title": "Digital Marketing Strategies",
    "type": "Local",
    "staff": 34,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 1,
    "venue": "Villefranche-sur-Mer",
    "fee": "300",
    "category": "Upcoming",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 94,
    "creator": "Lamond Zack",
    "directorate": "Employee Training",
    "title": "Mobile App Development",
    "type": "International",
    "staff": 31,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 8,
    "venue": "Lyubotyn",
    "fee": "300",
    "category": "Upcoming",
    "description": "Improve your public speaking skills"
  }, {
    "_id": 95,
    "creator": "Winny Vernazza",
    "directorate": "Learning and Development",
    "title": "Project Management Basics",
    "type": "Regional",
    "staff": 50,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 11,
    "venue": "Toutosa",
    "fee": "000",
    "category": "Upcoming",
    "description": "Learn how to code in Python"
  }, {
    "_id": 96,
    "creator": "Rafaellle Eldridge",
    "directorate": "Talent Development",
    "title": "Cybersecurity Essentials",
    "type": "International",
    "staff": 29,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 17,
    "venue": "Sopo",
    "fee": "000",
    "category": "Completed",
    "description": "Become a certified yoga instructor"
  }, {
    "_id": 97,
    "creator": "Rea Crookston",
    "directorate": "Training Operations",
    "title": "Machine Learning Fundamentals",
    "type": "Regional",
    "staff": 45,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 4,
    "venue": "Tõrva",
    "fee": "000",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 98,
    "creator": "Brietta Batchellor",
    "directorate": "Talent Development",
    "title": "Introduction to Python Programming",
    "type": "Local",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 3,
    "venue": "Escazú",
    "fee": "500",
    "category": "Pending",
    "description": "Master the art of digital marketing"
  }, {
    "_id": 99,
    "creator": "Myca Stallan",
    "directorate": "Talent Development",
    "title": "Graphic Design Principles",
    "type": "National",
    "staff": 25,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 18,
    "venue": "Loandjili",
    "fee": "000",
    "category": "Cancelled",
    "description": "Learn how to code in Python"
  }, {
    "_id": 100,
    "creator": "Kaine Lilleyman",
    "directorate": "Learning and Development",
    "title": "Graphic Design Principles",
    "type": "International",
    "staff": 5,
    "start": "9/2/2024",
    "end": "9/14/2024",
    "period": 0,
    "venue": "Qohord-e Bālā",
    "fee": "000",
    "category": "Completed",
    "description": "Improve your public speaking skills"
  }]