export default {
    "data": [
        {
            "POST_ID": 634,
            "POST_TYPE": 1,
            "POST_CONTENT": "<b>Renewal of contract appointment</b>",
            "POSTED_BY": 2319,
            "DATE_POSTED": 1704804351,
            "COMMENT_COUNT": 0,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "ONUIGBO",
            "FIRST_NAME": "SAMUEL",
            "FILE_NAME": "ONUIGBO-SAMUEL-OJODU-P.883.JPG",
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "01/09/24",
            "DIRECTORATE": "DIRECTORATE OF AERODROME & AIRSPACE STANDARDS",
            "COMMENTS": null,
            "TOTAL_COMMENTS": 0
        },
        {
            "POST_ID": 633,
            "POST_TYPE": 1,
            "POST_CONTENT": "<p>Good day. </p><p>I just observed that my directorate reads DOLTS instead of DAWS, Abuja regional office.</p>",
            "POSTED_BY": 4639,
            "DATE_POSTED": 1704800455,
            "COMMENT_COUNT": 0,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "Haggai",
            "FIRST_NAME": "Longshak",
            "FILE_NAME": null,
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": "20220515_112614.jpg",
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "01/09/24",
            "DIRECTORATE": "DIRECTORATES OF OPERATIONS, LICENSING AND TRAINING STANDARDS",
            "COMMENTS": null,
            "TOTAL_COMMENTS": 0
        },
        {
            "POST_ID": 632,
            "POST_TYPE": 1,
            "POST_CONTENT": "<p>Good afternoon,</p><p>I am a staff of NCAA library, the name of my reporting officer Onyejose Fumnanya Gladys is not on the column for \"Select Reporting Officer\" on my Annual Performance Evaluation Report (APER). </p>",
            "POSTED_BY": 3551,
            "DATE_POSTED": 1704465176,
            "COMMENT_COUNT": 1,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "Ogalue",
            "FIRST_NAME": "Ifesinachi",
            "FILE_NAME": "20220515_112614.jpg",
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "01/05/24",
            "DIRECTORATE": "DG OFFICE",
            "COMMENTS": [
                {
                    "COMMENT_ID": 1969,
                    "POST_ID": 632,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 3551,
                    "MESSAGE": "Thank you in anticipation of your kind response.",
                    "DATE_POSTED": 1704465327,
                    "LAST_NAME": "Ogalue",
                    "FIRST_NAME": "Ifesinachi",
                    "OTHER_NAMES": "Rita",
                    "FILE_NAME": "20220515_112614.jpg"
                }
            ],
            "TOTAL_COMMENTS": 1
        },
        {
            "POST_ID": 631,
            "POST_TYPE": 1,
            "POST_CONTENT": "<p>Good afternoon.</p><p>I applied for my annual leave which is to commence on 29th December, 2023, but up to now it has not been approved. Kindly look into my issue.</p><p>Thank you in anticipation of your kind response. </p>",
            "POSTED_BY": 4626,
            "DATE_POSTED": 1703684347,
            "COMMENT_COUNT": 1,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "Abbas",
            "FIRST_NAME": "Dikko",
            "FILE_NAME": null,
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "12/27/23",
            "DIRECTORATE": "DG OFFICE",
            "COMMENTS": [
                {
                    "COMMENT_ID": 1966,
                    "POST_ID": 631,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 4626,
                    "MESSAGE": "Good morning. Thank you for the response. I will discuss it further with my approving officer.",
                    "DATE_POSTED": 1703754209,
                    "LAST_NAME": "Abbas",
                    "FIRST_NAME": "Dikko",
                    "OTHER_NAMES": "",
                    "FILE_NAME": null
                }
            ],
            "TOTAL_COMMENTS": 1
        },
        {
            "POST_ID": 630,
            "POST_TYPE": 1,
            "POST_CONTENT": "<p>Kindly correct the following observations from my staff file, pay slip, and staff nominal roll:</p><p>Staff ID NCAA/P.1563\n</p><p>First name: HASHIM </p><p>Surname: KABIR\n</p><p>DIVISION NAME: DAAS (KANO)\n</p><p>\nRANK: AERODROME SAFETY\nINSPECTOR I</p><p><br></p><p>Thank you for your cooperation.</p>",
            "POSTED_BY": 2349,
            "DATE_POSTED": 1702892230,
            "COMMENT_COUNT": 6,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "HASHIM",
            "FIRST_NAME": "KABIR",
            "FILE_NAME": "IMG_20200219_192021.jpg",
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "12/18/23",
            "DIRECTORATE": "DIRECTORATE OF AERODROME & AIRSPACE STANDARDS",
            "COMMENTS": [
                {
                    "COMMENT_ID": 1967,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A kind reminder, please.",
                    "DATE_POSTED": 1703843648,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
                {
                    "COMMENT_ID": 1968,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A reminder, please.",
                    "DATE_POSTED": 1704464714,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
                {
                    "COMMENT_ID": 1968,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A reminder, please.",
                    "DATE_POSTED": 1704464714,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
                {
                    "COMMENT_ID": 1968,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A reminder, please.",
                    "DATE_POSTED": 1704464714,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
                {
                    "COMMENT_ID": 1968,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A reminder, please.",
                    "DATE_POSTED": 1704464714,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
                {
                    "COMMENT_ID": 1968,
                    "POST_ID": 630,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 2349,
                    "MESSAGE": "A reminder, please.",
                    "DATE_POSTED": 1704464714,
                    "LAST_NAME": "HASHIM",
                    "FIRST_NAME": "KABIR",
                    "OTHER_NAMES": " ",
                    "FILE_NAME": "IMG_20200219_192021.jpg"
                },
            ],
            "TOTAL_COMMENTS": 2
        },
        {
            "POST_ID": 629,
            "POST_TYPE": 1,
            "POST_CONTENT": "Good day, please my unit is AERODROME ENGINEERING and not AERO MET and also my present posting is KANO REGIONAL OFFICE not ABUJA REGIONAL OFFICE. Thank you.",
            "POSTED_BY": 3492,
            "DATE_POSTED": 1702644309,
            "COMMENT_COUNT": 2,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": 1,
            "LAST_NAME": "Mohammed",
            "FIRST_NAME": "Ahmad",
            "FILE_NAME": "PASSPORT2.jpg",
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "12/15/23",
            "DIRECTORATE": "DIRECTORATE OF AERODROME & AIRSPACE STANDARDS",
            "COMMENTS": [
                {
                    "COMMENT_ID": 1963,
                    "POST_ID": 629,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 3492,
                    "MESSAGE": "I am Mohammed Adamu AHMAD",
                    "DATE_POSTED": 1702644365,
                    "LAST_NAME": "Mohammed",
                    "FIRST_NAME": "Ahmad",
                    "OTHER_NAMES": "Adamu",
                    "FILE_NAME": "PASSPORT2.jpg"
                },
                {
                    "COMMENT_ID": 1964,
                    "POST_ID": 629,
                    "THREAD_ID": null,
                    "LIKES_COUNT": 0,
                    "USER_ID": 3492,
                    "MESSAGE": "NCAA/P.2143. Thank you",
                    "DATE_POSTED": 1702644387,
                    "LAST_NAME": "Mohammed",
                    "FIRST_NAME": "Ahmad",
                    "OTHER_NAMES": "Adamu",
                    "FILE_NAME": "PASSPORT2.jpg"
                }
            ],
            "TOTAL_COMMENTS": 2
        },
        {
            "POST_ID": 628,
            "POST_TYPE": 1,
            "POST_CONTENT": "Good day, I have tried several times to apply for my annual leave but it keeps failing, the handover aspect of the application js where I can't access all through this week",
            "POSTED_BY": 2950,
            "DATE_POSTED": 1702638144,
            "COMMENT_COUNT": 0,
            "IS_ATTACHMENT_ADDED": null,
            "SYSTEM_POSTED": 0,
            "TIMES_REPORTED": null,
            "LAST_NAME": "KAIGAMA",
            "FIRST_NAME": "ADAM",
            "FILE_NAME": "adamspp1.jpg",
            "POST_PRIVACY_SETTINGS": 1,
            "POST_FILE_NAME": null,
            "POST_REPORTED_ID": null,
            "DATE_ADDED": "12/15/23",
            "DIRECTORATE": "DIRECTORATE OFPUBLIC AFFAIRS &  COSUMER PROTECTION",
            "COMMENTS": null,
            "TOTAL_COMMENTS": 0
        }
    ]
}